cif_mag.dic

The changes in this PR are inspired by the discussion in https://github.com/COMCIFS/cif_core/issues/335.
I chose the form without the apostrophe (`Jones faithful notation` instead `Jones' faithful notation`) since this form is used in a recent (2020) publication regarding the extension of Hall symbols of crystallographic space groups to magnetic space groups (https://doi.org/10.1107/S1600576720015897).

Change several instances of "Jones-Faithful notation" to "Jones faithful notation"

---

cif_mag.dic

These values need to be quoted to not be recognised as list data structures.

Quote _type.dimension attribute values

---

cif_mag.dic

The _category.key_id attribute is no longer supported and should thus be removed. Note, however, that no information is lost since the same key data names are also listed using the _category_key.name attribute.

Remove the _category.key_id attribute

---

cif_mag.dic

Fix the _type.purpose attribute of the _atom_site_rotation.crystalaxis_z data item.

Fix the _type.purpose attribute of _atom_site_rotation.crystalaxis_z

---

cif_mag.dic

Dashes are not allowed in object id. The id of the _space_group.name_H-M_alt data item from the CIF_CORE dictionary is already changes in a similar way.

Change the object id of the _parent_space_group.name_H-M_alt data item.

---

cif_mag.dic

According to the DDLm reference dictionary, Matrix data items must have numeric values. Hopefully, the 'Real' type is sufficient.

Change content type of matrices from 'Text' to 'Real'

---

cif_mag.dic

Both the importing definition and the imported save frame contains the _definition.update attribute. This is not allowed under the default import behaviour (exit on duplicate). Removing this attribute from the dictionary definitions is one way of solving this issue, but a different approach might also be suitable (e.g. replace on import, ignore on import).

Remove several _definition.update attributes to resolve import issues.

---

cif_mag.dic

I overlooked this change in PR  #39.

Redefine examples as matrices instead of text fields

---

cif_mag.dic

The `_atom_site_Fourier_wave_vector.q[123]_coeff` and `_atom_site_Fourier_wave_vector.q_coeff` data items are defined both in the this dictionary and in the imported `MS_DIC` **(although possibly with different semantics!)**. However, since the save frame names of these data items are different, both definitions are retained during the initial merge.
If you prefer, I can change all of the save frame names to not have the  double underscore or we can do it in a separate PR since those changes will be mainly cosmetic in whereas this one has some semantic implications.

Change the prefix of some save frames from 'save__' to 'save_'.

---

cif_mag.dic

According to the updated specification of the DDLm `Version` content type, the minor version number is required.

Update version numbers to conform to SemVer 2.0.0.

---

cif_mag.dic

This PR fixes the following issues:
* Corrects the name of the `Head` save frame from the `cif_ms.dic` dictionary. Previously, the data block name was incorrectly provided.
* Add the "Ignore" on duplicate flag to allow the import of save frames from the `cif_ms.dic` dictionary. This is probably the intended behaviour. Note, that under this mode, even if the definition of a duplicate category is ignored, non-duplicate items from that category are still imported.
Additional things to address:
* In order for the "Ignore" flag to function as intended, the `ATOM_SITE_FOURIER_WAVE_VECTOR` category key had to be explicitly specified in this dictionary as well (that part of the definition was copied from the `cif_ms.dic` dictionary. Maybe it would make sense to also copy the full definition of …

Fix import issues

---

cif_mag.dic

The current "main" branch was re-output using `julia_cif_tools/pretty_print.jl` , then the result was compared to the source using `julia_cif_tools/compare.jl -w -c` (no whitespace or case differences considered significant) which found no differences.

Pretty-print dictionary according to style rules.

---

cif_mag.dic

This PR updates symop definitions so they match those in the `CIF_CORE` dictionary.
Note, that the assigned source values differ from the default ones, therefore this might conflict with PR https://github.com/COMCIFS/magnetic_dic/pull/46.

Declare symops definitions to be recorded with the 'Encode' purpose.

---

cif_mag.dic

As per change document from @brantonc : 
> (1) The descriptions of several entries say “See _space_group_magn_number_OG for a description of magnetic space groups (MSGs).”  Somehow, though this tag was prepared in an early magCIF draft, it was never transferred into the final product.  We now create this tag.  But rather than including a description of MSG construct types in this new entry, we will provide it elsewhere (see #51 ).

Add missing _space_group_magn.number_OG definition.

---

cif_mag.dic

As per para (5) of update document provided by @brantonc , data names for holding the new UNI symbols are added.

Add new UNI symbols.

---

cif_mag.dic

(6) We update the description of `_space_group_magn.ssg_name` to clarify that the MSSG symbol is based on the UNI symbol rather than the BNS symbol of the basic MSG.  This has been the case since the inception of magCIF, though the UNI format was only recently formalized.

Mag cif update para 6

---

cif_mag.dic

Note that example has been reformatted to embed the BNS and UNI equivalent information, and the loop data names changed.
(8) We create the new tag `_space_group_magn.Hall_symbol` to accommodate the new magnetic Hall symbols created by Juan Rodriguez-Carvajal and collaborators.

Changes in para 8 of updated document.

---

cif_mag.dic

The original units were radians, but accepted practice appears to be degrees. All relevant software authors are happy for the units to change. We may need to advise COMCIFS of this small violation of our principles.
(9) Change the units from radians to degrees for the following tags:
```
_atom_site_moment.spherical_azimuthal
_atom_site_moment.spherical_polar
_atom_site_rotation.spherical_azimuthal
_atom_site_rotation.spherical_polar
```

Change units for describing angles.

---

cif_mag.dic

This PR mainly addresses inconsistencies in the definitions of the `_parent_space_group.child_transform_pp_abc` and `_parent_space_group.transform_pp_abc`  data items. Specifically, the attributes assigned to these items did not seem compatible with their human-readable definitions. I tried to fix it using similar data items (e.g. `_space_group_magn.transform_BNS_Pp_abc`) as a template.
Also, looking at other similar `*_pp_abc` items I noticed that they are often also accompanied by the `*_pp` item which records the transformation matrix. Maybe that was also the original intention with these items and the corresponding `_parent_space_group.child_transform_pp` and `_parent_space_group.transform_pp` items should be added?
Finally, I also changed the purpose of several other `*_pp_abc` items …

Fix `*_transform_pp_abc` items

---

cif_mag.dic

This PR updates id definitions so they match those in the `CIF_CORE` dictionary.
Note, that in some cases the assigned source values differ from the default ones, therefore this might conflict with PR https://github.com/COMCIFS/magnetic_dic/pull/46.

Update definitions of arbitrary id data items.

---

cif_mag.dic

This PR updates the `_atom_site_moment_Fourier.wave_vector_seq_id` data item definition to formally link to the `_atom_site_Fourier_wave_vector.seq_id` data item as described in the human-readable part of the definition.
Note, that it may be necessary to further update this data item since the `_atom_site_Fourier_wave_vector.seq_id` may change when resolving PR https://github.com/COMCIFS/Modulated_Structures/issues/14.
Note, that the assigned purpose and source values differ from the default ones, therefore this might conflict with PR https://github.com/COMCIFS/magnetic_dic/pull/46

Update definition of _atom_site_moment_Fourier.wave_vector_seq_id

---

cif_mag.dic

This PR changes the parent category of the `ATOM_SITE_FOURIER_WAVE_VECTOR` category from `MS_GROUP` to `MAGNETIC`. After the change in the parent category, the `ATOM_SITE_FOURIER_WAVE_VECTOR` had to be moved to adhere to the dictionary style guide child category ordering rules.
The `ATOM_SITE_FOURIER_WAVE_VECTOR`  category is originally defined in the `CIF_MS` dictionary and expanded/overwritten in this dictionary. However, since the `CIF_MS` dictionary is imported in full (head-in-head import), all top level categories from the `CIF_MS` dictionary become automatically reparented from `MS_GROUP` to `MAGNETIC`. Furthermore, the `MS_GROUP` head category is not imported at all, thus resulting in a missing parent category.

Fix parent of imported category

---

cif_mag.dic

This PR deals mostly with cosmetic changes.
The dotless data names were changed to the main dotted data names (e.g. `_cell_wave_vector_seq_id` to `_cell_wave_vector.seq_id`) in the human-readable text and examples since these are the preferred names.
Note, that this PR also inadvertently corrects some of the category examples since not all dotless names used in the examples are defined in the dictionaries (e.g. `_atom_site_moment_Fourier.atom_site_label` is defined while the `_atom_site_moment_Fourier_atom_site_label` alias is not).

Apply minor cosmetic changes

---

cif_mag.dic

This PR deals with the technical side of CIF/DDLm.
The currently declared DDLm version 3.11.09 is quite outdated while version 4.1.0 is the latest tagged version (see https://github.com/COMCIFS/cif_core/blob/3.2.0/ddl.dic, tag 3.2.0 of the CIF_CORE repository). For all practical purposes we are already using DDLm 4.1.0 (or even later) so simply updating it does not seem to break anything.

Declare the dictionary as conformant to DDLm version 4.1.0.

---

cif_mag.dic

This PR adds an evaluation method for the `_atom_site_Fourier_wave_vector.q3_coeff` data item.
Almost identical methods are provided for `_atom_site_Fourier_wave_vector.q1_coeff` and `_atom_site_Fourier_wave_vector.q2_coeff`, but not for `_atom_site_Fourier_wave_vector.q3_coeff`.

Add evaluation method for `_atom_site_Fourier_wave_vector.q3_coeff`

---

cif_mag.dic

This PR redefines the `_atom_site_moment_Fourier.wave_vector_seq_id` from `Text` to a non-negative `Integer` since such values are expected by various symmform data items (see definition of `_atom_site_moment_Fourier_param.cos_symmform` and the following comment https://github.com/COMCIFS/magnetic_dic/issues/67#issuecomment-1928842478).
The non-negative enumeration range of 0: was taken from the definition of the linked `_atom_site_Fourier_wave_vector.seq_id` data item from the Modulation dictionary. However, I am not completely sure if the authors intended to include 0 into the set of allowed integers or simply though that the enumeration range is exclusive. Please let me know if this should be redefined to exclude the 0.

Restrict the values of _atom_site_moment_Fourier.wave_vector_seq_id

---

cif_mag.dic

This PR aims at resolving issue #67.
This PR is currently marked as a draft since there are still a few minor issues with the symmform definitions that should be resolved.

Update symmform examples

---

cif_mag.dic

Many style changes and typos. Sorry for the number in a single PR, but most should be uncontroversial.
More significant changes:
save__space_group_magn.hall_symbol -> save_space_group_magn.hall_symbol (i.e. just one underscore).
"Analogous tags" for symCIF changed to coreCIF where they are present in the current core dictionary.
Definition updates changed to today's date (2024-03-13) only for these symCIF/coreCIF changes.

Mostly style changes for International Tables G.

---

cif_mag.dic

This PR updates all flag definitions to be more similar to the ones in `CIF_CORE`. The flag values are made case-sensitive, and are explicitly assigned the `State` purpose and `Assigned` source.
Note, that the assigned purpose and source values differ from the default ones, therefore this might conflict with PR #46.

Update definitions of flag items

---

cif_mag.dic

This PR contains one minor cosmetic change.
The earlier phrasing was probably added before the introduction of the `_atom_sites_rot_Fourier.axes_description` data item in the modulation dictionary, but since it is now properly defined there, a fully qualified reference seems more reasonable.
I did not modify the change dates nor added a new changelog message since this minor change can probably be viewed as part of the cosmetic changes which were just recently made by @nautolycus.

Add a more standard reference to _atom_sites_rot_Fourier.axes_description

---

cif_mag.dic

For items with _type.container Single the standard attributes are obtained by import of the general_su save fram in templ_attr.cif

Added standard uncertainty data items for Measurand quantities

---

cif_mag.dic

This PR should be merged only after merging PR https://github.com/COMCIFS/Modulated_Structures/pull/25!

Update CIF_MS import statement

---

cif_mag.dic

This PR updated the dictionary and head save frame names to follow the IUCr conventions (see https://github.com/COMCIFS/cif_core/issues/488).
It would be nice to merge this before the initial release of the dictionary.

Update dictionary and head save frame names
